build:
	mvn clean package

test:
	mvn test

docker-build:
	docker build -t java-cloud-devops:1.0 .

docker-run:
	docker run -d -p 8080:8080 java-cloud-devops:1.0

docker-push:
	docker push mircodocker14/java-cloud-devops:1.0