apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-cloud-app
  template:
    metadata:
      labels:
        app: java-cloud-app
    spec:
      containers:
      - name: app
        image: java-cloud-app
        ports:
        - containerPort: 8080
